name: CI/CD 

on:
 push:
  branches: [main]

jobs:
 job_one:
  name: Deploy
  runs-on: ubuntu-latest
  steps:
  - name: ssh connection
    uses: appleboy/ssh-action@master
    with:
     host: ${{ secrets.HOST }}
     key: ${{ secrets.SERVER_SECRET }}
     port: 22
     script: |
      cd /root/repodata/test1
      git pull origin main
      git status
